### ISSUE TITLE
Request for Details on Multi-Weather Dataset Generation

### ISSUE THREAD

**Issue by feichaiyu** [SeRAlab/Robust-and-Accurate-UV-map-based-Camouflage-Attack#1]
I am impressed by your work and particularly interested in the multi-weather dataset discussed in your paper. Could you please share more details on how this dataset was generated with CARLA, or provide access to the dataset?

Thank you for your time.

**Comment by zhoujiawei3** [comment]
We have uploaded links to our texture generation dataset and the NRP weight to the readme.txt. The details about the datasets can be found in the appendix of our paper.
