### ISSUE TITLE
Question about the Adversarial UV Map

### ISSUE THREAD

**Issue by JWLiang007** [SeRAlab/Robust-and-Accurate-UV-map-based-Camouflage-Attack#2]
Hello,

I have a question about obtaining the adversarial **Texture** UV map  in the following picture. Could you please guide me on the specific code I should run to achieve this?
![图片](https://github.com/user-attachments/assets/0bced751-f81e-4fcb-83bb-be32e6d6601a)

I followed the tutorial and was only able to obtain the texture in numpy form, as shown in the following source code link:

[src/textures/texture.npy
](https://github.com/SeRAlab/Robust-and-Accurate-UV-map-based-Camouflage-Attack/blob/6b7ce55181becc7302c47c9b08fbd285cf21e616/src/textures/texture.npy)

**Comment by zhoujiawei3** [comment]
We have uploaded **Post-processing to get the deployable UV map** in the readme.md to show how to get the image form of the texture. You can try it.
