### ISSUE TITLE
Questions about experimental replication of ACTIVE and DTA

### ISSUE THREAD

**Issue by qwc0121** [SeRAlab/Robust-and-Accurate-UV-map-based-Camouflage-Attack#3]
The source code of ACTIVE and DTA projects does not seem to be open on the Internet, did you build it yourself according to the network framework? If yes, could you provide the corresponding code? Thank you very much

**Comment by zhoujiawei3** [comment]
I just ask their author for the texture.

**Comment by qwc0121** [comment]
> I just ask their author for the texture.

Ok, I see. Thank you for your reply.

**Comment by 169200750** [comment]
Do you still have the DTA and ACTIVATE textures saved? If so, could you please send me a copy? Thank you.
